server:
  port: 8076

spring:
  application:
    name: wechat-ut

---
spring:
  profiles: local
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 600000
    password: 12345678
    jedis:
      pool:
        max-idle: 800
        min-idle: 20
        max-active: 80
        max-wait: 10000
logging:
  level:
    com.meihaofenqi: debug
  file: log/wechat-util-demo.log
wechat:
  appId: xxx
  appSecret: xxx
  token: xxx

---
spring:
  profiles: test
  redis:
    database: 1
    host: xxx
    port: 6380
    timeout: 600000
    password: xxx
    jedis:
      pool:
        max-idle: 800
        min-idle: 20
        max-active: 80
        max-wait: 10000
logging:
  level:
    com.meihaofenqi: debug
  file: /opt/project/wechat-util-demo.log
wechat:
  appId: xxx
  appSecret: xxx
  token: xxx
